### ISSUE TITLE
Add support for typing.Union

### ISSUE THREAD

**Issue by boralyl** [upsight/doctor#79]
There may be some cases where a parameter can be one of a few types.  The best example would be a parameter that can be a string or a None value.  Example:

```python
import typing
from doctor.types import string

MiddleName = string('The middle name of a person')
NullableMiddleName = typing.Union[MiddleName, None]
```

The `NullableMiddleName` type would allow a string value or a None value and validate properly.

**Comment by boralyl** [comment]
While `Union` would be nice, it does not provide any public attributes to determine if a type is a `Union`.  The `__args__` contains the types as a tuple.  It is possible to determine if a type is a Union, but it's a bit hacky:

```python
>>> from typing import Union
>>> from doctor.types import string
>>> A = string('A', max_length=1)
>>> B = string('B', max_length=2)
>>> C = Union[A, B]
>>> C.__args__
(<class 'doctor.types.String'>, <class 'doctor.types.String'>)
>>> C.__origin__
typing.Union
>>> getattr(C, '__origin__', None) is Union
True
>>> getattr(A, '__origin__', None) is Union
False
```

Instead I propose this functionality simply get's built into a new type that can handle validation and that type can be subclassed in order to create your own type.  e.g.

```python
>>> from doctor.types import AnyOfType, string
>>> A = string('A', max_length=1)
>>> B = string('B', max_length=2)
>>> class C(AnyOfType):
...   any_of = [A, B]
...
>>> # the value 'aa' could only be of type B, since type A has max_length of 1
>>> C('aa')
'aa'
>>> # Type B can't be longer than 2 chars
>>> C('aaa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/doctor/doctor/types.py", line 119, in __new__
    raise TypeSystemError(cls=cls, code='max_length')
doctor.errors.TypeSystemError: Must have no more than 2 characters.
```
